/* tslint:disable */
/* eslint-disable */
/**
 * Gentrace API
 * These API routes are designed to ingest events from clients.
 *
 * The version of the OpenAPI document: 0.12.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "../configuration";
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  RequestArgs,
  BaseAPI,
  RequiredError,
} from "../base";
// @ts-ignore
import { PipelinesGet200Response } from "../models";
// @ts-ignore
import { RunRequest } from "../models";
// @ts-ignore
import { RunResponse } from "../models";
// @ts-ignore
import { TestCaseGet200Response } from "../models";
// @ts-ignore
import { TestCasePatch200Response } from "../models";
// @ts-ignore
import { TestCasePost200Response } from "../models";
// @ts-ignore
import { TestCasePostRequest } from "../models";
// @ts-ignore
import { TestResultGet200Response } from "../models";
// @ts-ignore
import { TestResultGet200Response1 } from "../models";
// @ts-ignore
import { TestResultPost200Response } from "../models";
// @ts-ignore
import { TestResultPostRequest } from "../models";
// @ts-ignore
import { TestResultSimplePostRequest } from "../models";
// @ts-ignore
import { UpdateTestCase } from "../models";
/**
 * CoreApi - axios parameter creator
 * @export
 */
export const CoreApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @summary Get pipelines, optionally filtered by label
     * @param {string} [label] The label to filter pipelines by
     * @param {string} [slug] The slug to filter pipelines by
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    pipelinesGet: async (
      label?: string,
      slug?: string,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/pipelines`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (label !== undefined) {
        localVarQueryParameter["label"] = label;
      }

      if (slug !== undefined) {
        localVarQueryParameter["slug"] = slug;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Create a run
     * @param {RunRequest} runRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    runPost: async (
      runRequest: RunRequest,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'runRequest' is not null or undefined
      assertParamExists("runPost", "runRequest", runRequest);
      const localVarPath = `/run`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        runRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Get test cases for a pipeline
     * @param {string} [pipelineId] The ID of the Pipeline to retrieve test cases for
     * @param {string} [pipelineSlug] The slug of the Pipeline to retrieve test cases for
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    testCaseGet: async (
      pipelineId?: string,
      pipelineSlug?: string,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/test-case`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (pipelineId !== undefined) {
        localVarQueryParameter["pipelineId"] = pipelineId;
      }

      if (pipelineSlug !== undefined) {
        localVarQueryParameter["pipelineSlug"] = pipelineSlug;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Update an existing test case
     * @param {UpdateTestCase} updateTestCase
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    testCasePatch: async (
      updateTestCase: UpdateTestCase,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'updateTestCase' is not null or undefined
      assertParamExists("testCasePatch", "updateTestCase", updateTestCase);
      const localVarPath = `/test-case`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PATCH",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        updateTestCase,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Create a new test case
     * @param {TestCasePostRequest} testCasePostRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    testCasePost: async (
      testCasePostRequest: TestCasePostRequest,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'testCasePostRequest' is not null or undefined
      assertParamExists(
        "testCasePost",
        "testCasePostRequest",
        testCasePostRequest,
      );
      const localVarPath = `/test-case`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        testCasePostRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Get test result by ID
     * @param {string} resultId The ID of the test result to retrieve
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    testResultGet: async (
      resultId: string,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'resultId' is not null or undefined
      assertParamExists("testResultGet", "resultId", resultId);
      const localVarPath = `/test-result`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (resultId !== undefined) {
        localVarQueryParameter["resultId"] = resultId;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Create a new test result from runs
     * @param {TestResultPostRequest} testResultPostRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    testResultPost: async (
      testResultPostRequest: TestResultPostRequest,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'testResultPostRequest' is not null or undefined
      assertParamExists(
        "testResultPost",
        "testResultPostRequest",
        testResultPostRequest,
      );
      const localVarPath = `/test-result`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        testResultPostRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Get test result by ID
     * @param {string} resultId The ID of the test result to retrieve
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     */
    testResultSimpleGet: async (
      resultId: string,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'resultId' is not null or undefined
      assertParamExists("testResultSimpleGet", "resultId", resultId);
      const localVarPath = `/test-result-simple`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (resultId !== undefined) {
        localVarQueryParameter["resultId"] = resultId;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Create a new test result from test runs
     * @param {TestResultSimplePostRequest} testResultSimplePostRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    testResultSimplePost: async (
      testResultSimplePostRequest: TestResultSimplePostRequest,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'testResultSimplePostRequest' is not null or undefined
      assertParamExists(
        "testResultSimplePost",
        "testResultSimplePostRequest",
        testResultSimplePostRequest,
      );
      const localVarPath = `/test-result-simple`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        testResultSimplePostRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * CoreApi - functional programming interface
 * @export
 */
export const CoreApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = CoreApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary Get pipelines, optionally filtered by label
     * @param {string} [label] The label to filter pipelines by
     * @param {string} [slug] The slug to filter pipelines by
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async pipelinesGet(
      label?: string,
      slug?: string,
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<PipelinesGet200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.pipelinesGet(
        label,
        slug,
        options,
      );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     *
     * @summary Create a run
     * @param {RunRequest} runRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async runPost(
      runRequest: RunRequest,
      options?: AxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<RunResponse>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.runPost(
        runRequest,
        options,
      );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     *
     * @summary Get test cases for a pipeline
     * @param {string} [pipelineId] The ID of the Pipeline to retrieve test cases for
     * @param {string} [pipelineSlug] The slug of the Pipeline to retrieve test cases for
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async testCaseGet(
      pipelineId?: string,
      pipelineSlug?: string,
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<TestCaseGet200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.testCaseGet(
        pipelineId,
        pipelineSlug,
        options,
      );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     *
     * @summary Update an existing test case
     * @param {UpdateTestCase} updateTestCase
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async testCasePatch(
      updateTestCase: UpdateTestCase,
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<TestCasePatch200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.testCasePatch(
        updateTestCase,
        options,
      );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     *
     * @summary Create a new test case
     * @param {TestCasePostRequest} testCasePostRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async testCasePost(
      testCasePostRequest: TestCasePostRequest,
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<TestCasePost200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.testCasePost(
        testCasePostRequest,
        options,
      );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     *
     * @summary Get test result by ID
     * @param {string} resultId The ID of the test result to retrieve
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async testResultGet(
      resultId: string,
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<TestResultGet200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.testResultGet(
        resultId,
        options,
      );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     *
     * @summary Create a new test result from runs
     * @param {TestResultPostRequest} testResultPostRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async testResultPost(
      testResultPostRequest: TestResultPostRequest,
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<TestResultPost200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.testResultPost(
        testResultPostRequest,
        options,
      );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     *
     * @summary Get test result by ID
     * @param {string} resultId The ID of the test result to retrieve
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     */
    async testResultSimpleGet(
      resultId: string,
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<TestResultGet200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.testResultSimpleGet(resultId, options);
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     *
     * @summary Create a new test result from test runs
     * @param {TestResultSimplePostRequest} testResultSimplePostRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async testResultSimplePost(
      testResultSimplePostRequest: TestResultSimplePostRequest,
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<TestResultPost200Response>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.testResultSimplePost(
          testResultSimplePostRequest,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
  };
};

/**
 * CoreApi - factory interface
 * @export
 */
export const CoreApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = CoreApiFp(configuration);
  return {
    /**
     *
     * @summary Get pipelines, optionally filtered by label
     * @param {string} [label] The label to filter pipelines by
     * @param {string} [slug] The slug to filter pipelines by
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    pipelinesGet(
      label?: string,
      slug?: string,
      options?: any,
    ): AxiosPromise<PipelinesGet200Response> {
      return localVarFp
        .pipelinesGet(label, slug, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Create a run
     * @param {RunRequest} runRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    runPost(runRequest: RunRequest, options?: any): AxiosPromise<RunResponse> {
      return localVarFp
        .runPost(runRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Get test cases for a pipeline
     * @param {string} [pipelineId] The ID of the Pipeline to retrieve test cases for
     * @param {string} [pipelineSlug] The slug of the Pipeline to retrieve test cases for
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    testCaseGet(
      pipelineId?: string,
      pipelineSlug?: string,
      options?: any,
    ): AxiosPromise<TestCaseGet200Response> {
      return localVarFp
        .testCaseGet(pipelineId, pipelineSlug, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Update an existing test case
     * @param {UpdateTestCase} updateTestCase
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    testCasePatch(
      updateTestCase: UpdateTestCase,
      options?: any,
    ): AxiosPromise<TestCasePatch200Response> {
      return localVarFp
        .testCasePatch(updateTestCase, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Create a new test case
     * @param {TestCasePostRequest} testCasePostRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    testCasePost(
      testCasePostRequest: TestCasePostRequest,
      options?: any,
    ): AxiosPromise<TestCasePost200Response> {
      return localVarFp
        .testCasePost(testCasePostRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Get test result by ID
     * @param {string} resultId The ID of the test result to retrieve
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    testResultGet(
      resultId: string,
      options?: any,
    ): AxiosPromise<TestResultGet200Response> {
      return localVarFp
        .testResultGet(resultId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Create a new test result from runs
     * @param {TestResultPostRequest} testResultPostRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    testResultPost(
      testResultPostRequest: TestResultPostRequest,
      options?: any,
    ): AxiosPromise<TestResultPost200Response> {
      return localVarFp
        .testResultPost(testResultPostRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Get test result by ID
     * @param {string} resultId The ID of the test result to retrieve
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     */
    testResultSimpleGet(
      resultId: string,
      options?: any,
    ): AxiosPromise<TestResultGet200Response> {
      return localVarFp
        .testResultSimpleGet(resultId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Create a new test result from test runs
     * @param {TestResultSimplePostRequest} testResultSimplePostRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    testResultSimplePost(
      testResultSimplePostRequest: TestResultSimplePostRequest,
      options?: any,
    ): AxiosPromise<TestResultPost200Response> {
      return localVarFp
        .testResultSimplePost(testResultSimplePostRequest, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * CoreApi - object-oriented interface
 * @export
 * @class CoreApi
 * @extends {BaseAPI}
 */
export class CoreApi extends BaseAPI {
  /**
   *
   * @summary Get pipelines, optionally filtered by label
   * @param {string} [label] The label to filter pipelines by
   * @param {string} [slug] The slug to filter pipelines by
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CoreApi
   */
  public pipelinesGet(
    label?: string,
    slug?: string,
    options?: AxiosRequestConfig,
  ) {
    return CoreApiFp(this.configuration)
      .pipelinesGet(label, slug, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Create a run
   * @param {RunRequest} runRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CoreApi
   */
  public runPost(runRequest: RunRequest, options?: AxiosRequestConfig) {
    return CoreApiFp(this.configuration)
      .runPost(runRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Get test cases for a pipeline
   * @param {string} [pipelineId] The ID of the Pipeline to retrieve test cases for
   * @param {string} [pipelineSlug] The slug of the Pipeline to retrieve test cases for
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CoreApi
   */
  public testCaseGet(
    pipelineId?: string,
    pipelineSlug?: string,
    options?: AxiosRequestConfig,
  ) {
    return CoreApiFp(this.configuration)
      .testCaseGet(pipelineId, pipelineSlug, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Update an existing test case
   * @param {UpdateTestCase} updateTestCase
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CoreApi
   */
  public testCasePatch(
    updateTestCase: UpdateTestCase,
    options?: AxiosRequestConfig,
  ) {
    return CoreApiFp(this.configuration)
      .testCasePatch(updateTestCase, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Create a new test case
   * @param {TestCasePostRequest} testCasePostRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CoreApi
   */
  public testCasePost(
    testCasePostRequest: TestCasePostRequest,
    options?: AxiosRequestConfig,
  ) {
    return CoreApiFp(this.configuration)
      .testCasePost(testCasePostRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Get test result by ID
   * @param {string} resultId The ID of the test result to retrieve
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CoreApi
   */
  public testResultGet(resultId: string, options?: AxiosRequestConfig) {
    return CoreApiFp(this.configuration)
      .testResultGet(resultId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Create a new test result from runs
   * @param {TestResultPostRequest} testResultPostRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CoreApi
   */
  public testResultPost(
    testResultPostRequest: TestResultPostRequest,
    options?: AxiosRequestConfig,
  ) {
    return CoreApiFp(this.configuration)
      .testResultPost(testResultPostRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Get test result by ID
   * @param {string} resultId The ID of the test result to retrieve
   * @param {*} [options] Override http request option.
   * @deprecated
   * @throws {RequiredError}
   * @memberof CoreApi
   */
  public testResultSimpleGet(resultId: string, options?: AxiosRequestConfig) {
    return CoreApiFp(this.configuration)
      .testResultSimpleGet(resultId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Create a new test result from test runs
   * @param {TestResultSimplePostRequest} testResultSimplePostRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CoreApi
   */
  public testResultSimplePost(
    testResultSimplePostRequest: TestResultSimplePostRequest,
    options?: AxiosRequestConfig,
  ) {
    return CoreApiFp(this.configuration)
      .testResultSimplePost(testResultSimplePostRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
