/* tslint:disable */
/* eslint-disable */
/**
 * Gentrace API
 * These API routes are designed to ingest events from clients.
 *
 * The version of the OpenAPI document: 0.9.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { TestCase } from "./test-case";

/**
 *
 * @export
 * @interface Pipeline
 */
export interface Pipeline {
  /**
   * The ID of the pipeline
   * @type {string}
   * @memberof Pipeline
   */
  id: string;
  /**
   * The date and time when the pipelinewas created
   * @type {string}
   * @memberof Pipeline
   */
  createdAt: string;
  /**
   * The date and time when the pipelinewas last updated
   * @type {string}
   * @memberof Pipeline
   */
  updatedAt: string;
  /**
   * The date and time when the pipelinewas archived, can be null if the pipelinehas not been archived
   * @type {string}
   * @memberof Pipeline
   */
  archivedAt?: string | null;
  /**
   * The array of test cases that belong to the pipeline
   * @type {Array<TestCase>}
   * @memberof Pipeline
   */
  cases: Array<TestCase>;
  /**
   * The labels attached to the pipeline
   * @type {Array<string>}
   * @memberof Pipeline
   */
  labels: Array<string>;
  /**
   * The name of the pipeline
   * @type {string}
   * @memberof Pipeline
   */
  name: string;
  /**
   * The ID of the organization that owns the pipeline
   * @type {string}
   * @memberof Pipeline
   */
  organizationId: string;
  /**
   * The branch that the pipelineis associated with
   * @type {string}
   * @memberof Pipeline
   */
  branch?: string | null;
}
