/* tslint:disable */
/* eslint-disable */
/**
 * Gentrace API
 * These API routes are designed to ingest events from clients.
 *
 * The version of the OpenAPI document: 0.9.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { RunRequestStepRunsInnerProvider } from "./run-request-step-runs-inner-provider";

/**
 *
 * @export
 * @interface RunRequestStepRunsInner
 */
export interface RunRequestStepRunsInner {
  /**
   *
   * @type {RunRequestStepRunsInnerProvider}
   * @memberof RunRequestStepRunsInner
   */
  provider?: RunRequestStepRunsInnerProvider;
  /**
   *
   * @type {number}
   * @memberof RunRequestStepRunsInner
   */
  elapsedTime?: number;
  /**
   *
   * @type {string}
   * @memberof RunRequestStepRunsInner
   */
  startTime?: string;
  /**
   *
   * @type {string}
   * @memberof RunRequestStepRunsInner
   */
  endTime?: string;
}
