/* tslint:disable */
/* eslint-disable */
/**
 * Gentrace API
 * These API routes are designed to ingest events from clients.
 *
 * The version of the OpenAPI document: 0.11.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { StepRunProvider } from './step-run-provider';

/**
 * 
 * @export
 * @interface StepRun
 */
export interface StepRun {
    /**
     * 
     * @type {StepRunProvider}
     * @memberof StepRun
     */
    'provider'?: StepRunProvider;
    /**
     * 
     * @type {number}
     * @memberof StepRun
     */
    'elapsedTime'?: number;
    /**
     * 
     * @type {string}
     * @memberof StepRun
     */
    'startTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof StepRun
     */
    'endTime'?: string;
}

