/* tslint:disable */
/* eslint-disable */
/**
 * Gentrace API
 * These API routes are designed to ingest events from clients.
 *
 * The version of the OpenAPI document: 0.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TestSet } from './test-set';

/**
 * 
 * @export
 * @interface TestSetsGet200Response
 */
export interface TestSetsGet200Response {
    /**
     * 
     * @type {Array<TestSet>}
     * @memberof TestSetsGet200Response
     */
    'testSets': Array<TestSet>;
}

