/* tslint:disable */
/* eslint-disable */
/**
 * Gentrace API
 * These API routes are designed to ingest events from clients.
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TestCase } from './test-case';

/**
 * 
 * @export
 * @interface TestSet
 */
export interface TestSet {
    /**
     * The ID of the test set
     * @type {string}
     * @memberof TestSet
     */
    'id': string;
    /**
     * The date and time when the test set was created
     * @type {string}
     * @memberof TestSet
     */
    'createdAt': string;
    /**
     * The date and time when the test set was last updated
     * @type {string}
     * @memberof TestSet
     */
    'updatedAt': string;
    /**
     * The date and time when the test set was archived, can be null if the test set has not been archived
     * @type {string}
     * @memberof TestSet
     */
    'archivedAt'?: string | null;
    /**
     * The array of test cases that belong to the test set
     * @type {Array<TestCase>}
     * @memberof TestSet
     */
    'cases': Array<TestCase>;
    /**
     * The labels attached to the test set
     * @type {Array<string>}
     * @memberof TestSet
     */
    'labels': Array<string>;
    /**
     * The name of the test set
     * @type {string}
     * @memberof TestSet
     */
    'name': string;
    /**
     * The ID of the organization that owns the test set
     * @type {string}
     * @memberof TestSet
     */
    'organizationId': string;
    /**
     * The branch that the test set is associated with
     * @type {string}
     * @memberof TestSet
     */
    'branch'?: string | null;
}

