/* tslint:disable */
/* eslint-disable */
/**
 * Gentrace API
 * These API routes are designed to ingest events from clients.
 *
 * The version of the OpenAPI document: 0.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TestRun } from './test-run';
// May contain unused imports in some cases
// @ts-ignore
import { TestRunGet200ResponseStats } from './test-run-get200-response-stats';

/**
 * 
 * @export
 * @interface TestRunGet200Response
 */
export interface TestRunGet200Response {
    /**
     * 
     * @type {TestRun}
     * @memberof TestRunGet200Response
     */
    'testRun'?: TestRun;
    /**
     * 
     * @type {TestRunGet200ResponseStats}
     * @memberof TestRunGet200Response
     */
    'stats'?: TestRunGet200ResponseStats;
}

