/* tslint:disable */
/* eslint-disable */
/**
 * Gentrace API
 * These API routes are designed to ingest events from clients.
 *
 * The version of the OpenAPI document: 0.9.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TestCaseExpectedStepsInner
 */
export interface TestCaseExpectedStepsInner {
  /**
   * The key of the step
   * @type {string}
   * @memberof TestCaseExpectedStepsInner
   */
  key: string;
  /**
   * The output of the step
   * @type {string}
   * @memberof TestCaseExpectedStepsInner
   */
  output: string;
  /**
   * The inputs of the step
   * @type {{ [key: string]: string; }}
   * @memberof TestCaseExpectedStepsInner
   */
  inputs?: { [key: string]: string } | null;
}
