/* tslint:disable */
/* eslint-disable */
/**
 * Gentrace API
 * These API routes are designed to ingest events from clients.
 *
 * The version of the OpenAPI document: 0.6.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TestRunGet200ResponseStats
 */
export interface TestRunGet200ResponseStats {
    /**
     * 
     * @type {number}
     * @memberof TestRunGet200ResponseStats
     */
    'total': number;
    /**
     * 
     * @type {number}
     * @memberof TestRunGet200ResponseStats
     */
    'pending': number;
    /**
     * 
     * @type {number}
     * @memberof TestRunGet200ResponseStats
     */
    'failure': number;
    /**
     * 
     * @type {number}
     * @memberof TestRunGet200ResponseStats
     */
    'done': number;
}

