/* tslint:disable */
/* eslint-disable */
/**
 * Gentrace API
 * These API routes are designed to ingest events from clients.
 *
 * The version of the OpenAPI document: 0.24.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface EvaluatorV2
 */
export interface EvaluatorV2 {
  /**
   * The ID of the evaluator
   * @type {string}
   * @memberof EvaluatorV2
   */
  id: string;
  /**
   * The name of the evaluator
   * @type {string}
   * @memberof EvaluatorV2
   */
  name: string;
  /**
   * For evaluators with options scoring, the available options to choose from
   * @type {object}
   * @memberof EvaluatorV2
   */
  options?: object | null;
  /**
   * For heuristic evaluators, the heuristic function to use
   * @type {string}
   * @memberof EvaluatorV2
   */
  heuristicFn?: string | null;
  /**
   * For AI evaluators, the AI model to use
   * @type {string}
   * @memberof EvaluatorV2
   */
  aiModel?: string | null;
  /**
   * For AI evaluators, the prompt template that should be sent to the AI model
   * @type {string}
   * @memberof EvaluatorV2
   */
  aiPromptFormat?: string | null;
  /**
   * For human evaluators, the instructions for the human to follow
   * @type {string}
   * @memberof EvaluatorV2
   */
  humanPrompt?: string | null;
}
