/* tslint:disable */
/* eslint-disable */
/**
 * Gentrace API
 * These API routes are designed to ingest events from clients.
 *
 * The version of the OpenAPI document: 0.24.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { StringType } from "./string-type";
// May contain unused imports in some cases
// @ts-ignore
import { UrlType } from "./url-type";

/**
 * @type MetadataValueObject
 * @export
 */
export type MetadataValueObject =
  | ({ type: "string" } & StringType)
  | ({ type: "url" } & UrlType);
