/* tslint:disable */
/* eslint-disable */
/**
 * Gentrace API
 * These API routes are designed to ingest events from clients.
 *
 * The version of the OpenAPI document: 0.16.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { Pipeline } from "./pipeline";
// May contain unused imports in some cases
// @ts-ignore
import { PipelinesGet200ResponsePipelinesInnerAllOf } from "./pipelines-get200-response-pipelines-inner-all-of";
// May contain unused imports in some cases
// @ts-ignore
import { TestCase } from "./test-case";

/**
 * @type PipelinesGet200ResponsePipelinesInner
 * @export
 */
export type PipelinesGet200ResponsePipelinesInner = Pipeline &
  PipelinesGet200ResponsePipelinesInnerAllOf;
