/* tslint:disable */
/* eslint-disable */
/**
 * Gentrace API
 * These API routes are designed to ingest events from clients.
 *
 * The version of the OpenAPI document: 0.12.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { Pipeline } from "./pipeline";

/**
 *
 * @export
 * @interface PipelinesGet200Response
 */
export interface PipelinesGet200Response {
  /**
   *
   * @type {Array<Pipeline>}
   * @memberof PipelinesGet200Response
   */
  pipelines: Array<Pipeline>;
}
