/* tslint:disable */
/* eslint-disable */
/**
 * Gentrace API
 * These API routes are designed to ingest events from clients.
 *
 * The version of the OpenAPI document: 0.15.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { PipelinesGet200ResponsePipelinesInner } from "./pipelines-get200-response-pipelines-inner";

/**
 *
 * @export
 * @interface PipelinesGet200Response
 */
export interface PipelinesGet200Response {
  /**
   *
   * @type {Array<PipelinesGet200ResponsePipelinesInner>}
   * @memberof PipelinesGet200Response
   */
  pipelines: Array<PipelinesGet200ResponsePipelinesInner>;
}
