/* tslint:disable */
/* eslint-disable */
/**
 * Gentrace API
 * These API routes are designed to ingest events from clients.
 *
 * The version of the OpenAPI document: 0.24.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { MetadataValueObject } from "./metadata-value-object";

/**
 *
 * @export
 * @interface RunV2StepRunsInner
 */
export interface RunV2StepRunsInner {
  /**
   * The ID of the step run
   * @type {string}
   * @memberof RunV2StepRunsInner
   */
  stepRunId: string;
  /**
   * The ID of the step
   * @type {string}
   * @memberof RunV2StepRunsInner
   */
  stepId: string;
  /**
   * The name of the provider
   * @type {string}
   * @memberof RunV2StepRunsInner
   */
  providerName: string;
  /**
   * The name of the method being invoked
   * @type {string}
   * @memberof RunV2StepRunsInner
   */
  invocation: string;
  /**
   * The order of the step run. The last step has the highest \"order\" number.
   * @type {number}
   * @memberof RunV2StepRunsInner
   */
  order: number;
  /**
   * The parameters used by the model
   * @type {object}
   * @memberof RunV2StepRunsInner
   */
  modelParams: object;
  /**
   * The inputs of the run
   * @type {object}
   * @memberof RunV2StepRunsInner
   */
  inputs: object;
  /**
   * The outputs of the run
   * @type {object}
   * @memberof RunV2StepRunsInner
   */
  outputs: object;
  /**
   * The milliseconds to complete the run
   * @type {number}
   * @memberof RunV2StepRunsInner
   */
  elapsedTime: number;
  /**
   * The date and time when the run started
   * @type {string}
   * @memberof RunV2StepRunsInner
   */
  startTime: string;
  /**
   * The date and time when the run ended
   * @type {string}
   * @memberof RunV2StepRunsInner
   */
  endTime: string;
  /**
   * The cost of the run in USD
   * @type {number}
   * @memberof RunV2StepRunsInner
   */
  cost: number;
  /**
   *
   * @type {{ [key: string]: MetadataValueObject; }}
   * @memberof RunV2StepRunsInner
   */
  metadata?: { [key: string]: MetadataValueObject } | null;
}
