/* tslint:disable */
/* eslint-disable */
/**
 * Gentrace API
 * These API routes are designed to ingest events from clients.
 *
 * The version of the OpenAPI document: 0.27.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface RunPathSection
 */
export interface RunPathSection {
  /**
   *
   * @type {string}
   * @memberof RunPathSection
   */
  type: RunPathSectionTypeEnum;
  /**
   *
   * @type {string}
   * @memberof RunPathSection
   */
  name: string;
}

export const RunPathSectionTypeEnum = {
  Suite: "suite",
} as const;

export type RunPathSectionTypeEnum =
  (typeof RunPathSectionTypeEnum)[keyof typeof RunPathSectionTypeEnum];
