/* tslint:disable */
/* eslint-disable */
/**
 * Gentrace API
 * These API routes are designed to ingest events from clients.
 *
 * The version of the OpenAPI document: 0.18.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { SearchableStringInputAnyOf } from "./searchable-string-input-any-of";

/**
 *
 * @export
 * @interface SearchableStringInput
 */
export interface SearchableStringInput {
  /**
   *
   * @type {string}
   * @memberof SearchableStringInput
   */
  contains?: string;
  /**
   * For Postgres full text search
   * @type {string}
   * @memberof SearchableStringInput
   */
  search?: string;
  /**
   *
   * @type {string}
   * @memberof SearchableStringInput
   */
  startsWith?: string;
  /**
   *
   * @type {string}
   * @memberof SearchableStringInput
   */
  endsWith?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof SearchableStringInput
   */
  in?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof SearchableStringInput
   */
  notIn?: Array<string>;
  /**
   *
   * @type {string}
   * @memberof SearchableStringInput
   */
  mode?: SearchableStringInputModeEnum;
}

export const SearchableStringInputModeEnum = {
  Insensitive: "insensitive",
  Default: "default",
} as const;

export type SearchableStringInputModeEnum =
  (typeof SearchableStringInputModeEnum)[keyof typeof SearchableStringInputModeEnum];
