/* tslint:disable */
/* eslint-disable */
/**
 * Gentrace API
 * These API routes are designed to ingest events from clients.
 *
 * The version of the OpenAPI document: 0.18.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { SearchableUnixSecondsInputAnyOf } from "./searchable-unix-seconds-input-any-of";

/**
 *
 * @export
 * @interface SearchableUnixSecondsInput
 */
export interface SearchableUnixSecondsInput {
  /**
   * Timestamp in seconds since the UNIX epoch. Can be transformed into a Date object.
   * @type {number}
   * @memberof SearchableUnixSecondsInput
   */
  gt?: number;
  /**
   * Timestamp in seconds since the UNIX epoch. Can be transformed into a Date object.
   * @type {number}
   * @memberof SearchableUnixSecondsInput
   */
  gte?: number;
  /**
   * Timestamp in seconds since the UNIX epoch. Can be transformed into a Date object.
   * @type {number}
   * @memberof SearchableUnixSecondsInput
   */
  lt?: number;
  /**
   * Timestamp in seconds since the UNIX epoch. Can be transformed into a Date object.
   * @type {number}
   * @memberof SearchableUnixSecondsInput
   */
  lte?: number;
}
