/* tslint:disable */
/* eslint-disable */
/**
 * Gentrace API
 * These API routes are designed to ingest events from clients.
 *
 * The version of the OpenAPI document: 0.13.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TestEvaluator
 */
export interface TestEvaluator {
  /**
   *
   * @type {string}
   * @memberof TestEvaluator
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof TestEvaluator
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof TestEvaluator
   */
  updatedAt: string;
  /**
   *
   * @type {string}
   * @memberof TestEvaluator
   */
  archivedAt?: string | null;
  /**
   *
   * @type {string}
   * @memberof TestEvaluator
   */
  icon?: string | null;
  /**
   *
   * @type {string}
   * @memberof TestEvaluator
   */
  name: string;
  /**
   *
   * @type {object}
   * @memberof TestEvaluator
   */
  options: object | null;
  /**
   *
   * @type {string}
   * @memberof TestEvaluator
   */
  aiModel?: TestEvaluatorAiModelEnum;
  /**
   *
   * @type {string}
   * @memberof TestEvaluator
   */
  pipelineId: string;
  /**
   *
   * @type {string}
   * @memberof TestEvaluator
   */
  processorId?: string | null;
  /**
   *
   * @type {string}
   * @memberof TestEvaluator
   */
  heuristicFn?: string | null;
  /**
   *
   * @type {string}
   * @memberof TestEvaluator
   */
  aiPromptFormat?: string | null;
  /**
   *
   * @type {string}
   * @memberof TestEvaluator
   */
  humanPrompt?: string | null;
  /**
   *
   * @type {string}
   * @memberof TestEvaluator
   */
  who: TestEvaluatorWhoEnum;
  /**
   *
   * @type {string}
   * @memberof TestEvaluator
   */
  valueType: TestEvaluatorValueTypeEnum;
}

export const TestEvaluatorAiModelEnum = {
  _35: "OPENAI_3_5",
  _4: "OPENAI_4",
} as const;

export type TestEvaluatorAiModelEnum =
  (typeof TestEvaluatorAiModelEnum)[keyof typeof TestEvaluatorAiModelEnum];
export const TestEvaluatorWhoEnum = {
  Ai: "AI",
  Heuristic: "HEURISTIC",
  Human: "HUMAN",
} as const;

export type TestEvaluatorWhoEnum =
  (typeof TestEvaluatorWhoEnum)[keyof typeof TestEvaluatorWhoEnum];
export const TestEvaluatorValueTypeEnum = {
  Enum: "ENUM",
  Percentage: "PERCENTAGE",
} as const;

export type TestEvaluatorValueTypeEnum =
  (typeof TestEvaluatorValueTypeEnum)[keyof typeof TestEvaluatorValueTypeEnum];
