/* tslint:disable */
/* eslint-disable */
/**
 * Gentrace API
 * These API routes are designed to ingest events from clients.
 *
 * The version of the OpenAPI document: 0.12.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TestCasePost200ResponseOneOf1
 */
export interface TestCasePost200ResponseOneOf1 {
  /**
   * Number of created test cases
   * @type {number}
   * @memberof TestCasePost200ResponseOneOf1
   */
  creationCount?: number;
}
