/* tslint:disable */
/* eslint-disable */
/**
 * Gentrace API
 * These API routes are designed to ingest events from clients.
 *
 * The version of the OpenAPI document: 0.12.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TestCasePatch200Response
 */
export interface TestCasePatch200Response {
  /**
   * ID of the updated test case
   * @type {string}
   * @memberof TestCasePatch200Response
   */
  caseId?: string;
}
