/* tslint:disable */
/* eslint-disable */
/**
 * Gentrace API
 * These API routes are designed to ingest events from clients.
 *
 * The version of the OpenAPI document: 0.12.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { TestCasePost200ResponseOneOf } from "./test-case-post200-response-one-of";
// May contain unused imports in some cases
// @ts-ignore
import { TestCasePost200ResponseOneOf1 } from "./test-case-post200-response-one-of1";

/**
 * @type TestCasePost200Response
 * @export
 */
export type TestCasePost200Response =
  | TestCasePost200ResponseOneOf
  | TestCasePost200ResponseOneOf1;
