/* tslint:disable */
/* eslint-disable */
/**
 * Gentrace API
 * These API routes are designed to ingest events from clients.
 *
 * The version of the OpenAPI document: 0.11.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { TestResultGet200ResponseStats } from "./test-result-get200-response-stats";
// May contain unused imports in some cases
// @ts-ignore
import { TestRun } from "./test-run";

/**
 *
 * @export
 * @interface TestRunGet200Response
 */
export interface TestRunGet200Response {
  /**
   *
   * @type {TestRun}
   * @memberof TestRunGet200Response
   */
  testRun?: TestRun;
  /**
   *
   * @type {TestResultGet200ResponseStats}
   * @memberof TestRunGet200Response
   */
  stats?: TestResultGet200ResponseStats;
}
