/* tslint:disable */
/* eslint-disable */
/**
 * Gentrace API
 * These API routes are designed to ingest events from clients.
 *
 * The version of the OpenAPI document: 0.27.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { RunPathSection } from "./run-path-section";

/**
 *
 * @export
 * @interface TestRun
 */
export interface TestRun {
  /**
   *
   * @type {string}
   * @memberof TestRun
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof TestRun
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof TestRun
   */
  updatedAt: string;
  /**
   *
   * @type {string}
   * @memberof TestRun
   */
  caseId: string;
  /**
   *
   * @type {string}
   * @memberof TestRun
   */
  resultId: string;
  /**
   *
   * @type {Array<RunPathSection>}
   * @memberof TestRun
   */
  path?: Array<RunPathSection> | null;
}
