/* tslint:disable */
/* eslint-disable */
/**
 * Gentrace API
 * These API routes are designed to ingest events from clients.
 *
 * The version of the OpenAPI document: 0.27.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateFeedbackV2
 */
export interface UpdateFeedbackV2 {
  /**
   * The score of the feedback, ranging from 0 to 1
   * @type {number}
   * @memberof UpdateFeedbackV2
   */
  score?: number;
  /**
   * Optional details about the feedback
   * @type {string}
   * @memberof UpdateFeedbackV2
   */
  details?: string | null;
}
