/* tslint:disable */
/* eslint-disable */
/**
 * Gentrace API
 * These API routes are designed to ingest events from clients.
 *
 * The version of the OpenAPI document: 0.27.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UrlType
 */
export interface UrlType {
  /**
   *
   * @type {string}
   * @memberof UrlType
   */
  type: UrlTypeTypeEnum;
  /**
   *
   * @type {string}
   * @memberof UrlType
   */
  url: string;
  /**
   *
   * @type {string}
   * @memberof UrlType
   */
  text: string;
}

export const UrlTypeTypeEnum = {
  Url: "url",
} as const;

export type UrlTypeTypeEnum =
  (typeof UrlTypeTypeEnum)[keyof typeof UrlTypeTypeEnum];
