/* tslint:disable */
/* eslint-disable */
/**
 * Gentrace API
 * These API routes are designed to ingest events from clients.
 *
 * The version of the OpenAPI document: 0.27.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface V2EvaluationsBulkPost200Response
 */
export interface V2EvaluationsBulkPost200Response {
  /**
   *
   * @type {number}
   * @memberof V2EvaluationsBulkPost200Response
   */
  count: number;
}
