/* tslint:disable */
/* eslint-disable */
/**
 * Gentrace API
 * These API routes are designed to ingest events from clients.
 *
 * The version of the OpenAPI document: 0.27.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { FolderV2 } from "./folder-v2";

/**
 *
 * @export
 * @interface V2FoldersGet200Response
 */
export interface V2FoldersGet200Response {
  /**
   *
   * @type {Array<FolderV2>}
   * @memberof V2FoldersGet200Response
   */
  data: Array<FolderV2>;
}
