/* tslint:disable */
/* eslint-disable */
/**
 * Gentrace API
 * These API routes are designed to ingest events from clients.
 *
 * The version of the OpenAPI document: 0.27.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { EvaluationV3 } from "./evaluation-v3";

/**
 *
 * @export
 * @interface V3EvaluationsGet200Response
 */
export interface V3EvaluationsGet200Response {
  /**
   *
   * @type {Array<EvaluationV3>}
   * @memberof V3EvaluationsGet200Response
   */
  data?: Array<EvaluationV3>;
}
