name: Build and publish package

on:
  workflow_dispatch:
      
permissions:
  contents: write
  pull-requests: write

jobs:
  generate:
    name: Generate SDKs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
        
    - uses: actions/setup-node@v3
      with:
        node-version: '18.15.0'
        cache: 'yarn'
        cache-dependency-path: yarn.lock
   
    - name: Install and build
      run: |
        yarn install
        yarn build
        
    - name: Publish package to NPM
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}" > .npmrc
        npm publish
        