name: Pull request check

on: [push, pull_request]

jobs:
  jest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["18.15.0", "16.14.1"]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: ⎔ Setup pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 9.0.6

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build assets
        run: pnpm -w run build

      - name: Run tests
        run: pnpm run test
