name: Pull request check

on: [push, pull_request]

jobs:
  jest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["18.15.0"]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: ⎔ Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.0.6

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build assets
        run: pnpm -w run build

      # Will fail if exit code > 0, indicating a POTENTIAL breaking change. If you're updating the types,
      # you must manually commit the changes with npx api-extractor run --local and repush. This
      # is an opportunity to review the changes and commit them manually.
      - name: Check API changes
        run: cd packages/core && npx api-extractor run --diagnostics --verbose

      - name: Run tests
        run: pnpm run test
