name: Pull request check

on: [push, pull_request]

jobs:
  jest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'
          cache: 'npm'
          cache-dependency-path: package/package-lock.json
        if: ${{ steps.release.outputs['package--release_created'] }}

      - name: Install and build
        run: |
          cd package
          npm ci
          npm run build

      - name: Run Jest tests
        run: |
          cd package
          npm run test